# ===================================================================
#DOCKERIZED POSTGRESQL CONFIGURATION
# ===================================================================
spring.config.import=optional:file:server/.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# jwt
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
app.jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
